website/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import login_required, current_user
from .form import RequestForm
from . import db
from .models import Plasma, User
 
views = Blueprint('views',__name__)

@views.route('/')
def home():
    return render_template("home.html", user=current_user)

@views.route('/Donor')
def Donor():
    return render_template("Donor.html", user=current_user)

@views.route('/info-plasma')
def info_plasma():
    return render_template("plasma.html", user=current_user)

@views.route('/recipient')
def recipient():
    return render_template("recipient.html", user=current_user)


@views.route('/board', methods=['GET'])
@login_required
def Board():
    plasma = Plasma.query.all()
    return render_template("board.html", plasma=plasma, user=current_user)

@views.route('/request', methods=['GET', 'POST'])
@login_required
def Request():
    form = RequestForm()
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        reg_no = request.form.get('reg_no')
        blood_group = request.form.get('blood_group')
        date_details = request.form.get('date_details')
        address = request.form.get('address')
        details = request.form.get('details')
        entry = Plasma.query.order_by(Plasma.id)
        new_entry = Plasma(name=form.name.data, email=form.email.data, reg_no=form.reg_no.data, blood_group=form.blood_group.data, date_details=form.date_details.data, address=form.address.data, details=form.details.data)
        db.session.add(new_entry)
        db.session.commit()
        flash('Request Posted', category='success')
        return redirect(url_for('views.Board'))
    return render_template("apply.html", form=form, user=current_user)

@views.route('/delete/<int:id>')
@login_required
def delete(id):
    entry_to_delete = Plasma.query.get_or_404(id)
    id =  current_user.email
    if id == entry_to_delete.email:
        try:
            db.session.delete(entry_to_delete)
            db.session.commit()
            flash('Request Successfully Deleted!!', category='success')
            return redirect(url_for('views.Board'))
        except:
            flash('Whoops! There was a problem deleting the request!', category='error')
            return redirect(url_for('views.Board'))
    else:
        flash('You are not authorised!!', category='error')
        return redirect(url_for('views.Board'))

@views.route('/request-update/<int:id>', methods=['GET', 'POST'])
@login_required
def request_update(id):
    form = RequestForm()
    request_to_update = Plasma.query.get_or_404(id)
    if request.method == "POST":
        request_to_update.email = request.form.get('email')
        request_to_update.name = request.form.get('name')
        request_to_update.reg_no = request.form.get('reg_no')
        request_to_update.blood_group = request.form.get('blood_group')
        request_to_update.date_details = request.form.get('date_details')
        request_to_update.address = request.form.get('address')
        request_to_update.details = request.form.get('details')
        try:
            db.session.commit()
            flash("Request Updated Successfully!", category = 'success')
            return redirect('/board')
        except:
            flash("Error! There was a problem updating your profile!", category = 'error') 
            return redirect('/board')
    else:
        return render_template("update1.html", form=form, request_to_update=request_to_update, user=current_user)


@views.route('/dashboard')
@login_required
def dashboard():
    users = User.query.all()
    return render_template("dashboard.html", users=users, user=current_user)

@views.route('/terms')
def terms():
    return render_template("terms.html", user=current_user)

@views.route('/privacy')
def privacy():
    return render_template("privacy.html", user=current_user)

@views.route('/faq')
def faq():
    return render_template("faq.html", user=current_user)

website/templates/Register.html
{% extends "base.html" %} {% block title %}Register{% endblock %}
{% block content %}

<br>
<br>
<br>
 <h3 align="centre">{{title}}</h3>
<form action=""  method="POST">
        <p>{{ form1.name.label }} <br>
           {{ form1.name(size=30) }} </p>
         
        <p>{{ form1.email.label }} <br>
           {{ form1.email(size=100) }} </p>

        <p>{{ form1.password.label }} <br>
           {{ form1.password(size=50) }} </p>

        <p>{{ form1.blood_group.label }} <br>
           {{ form1.blood_group(size=10) }} </p>

        <p>{{ form1.age.label }} <br>
           {{ form1.age }} </p>

       <br> <p>{{ form1.submit() }}</p>

</form>

{% endblock %}

website/templates/apply.html
{% extends "base.html" %} {% block title %}Request-Application{% endblock %}
{% block content %}

<br>
<h3 align="center" class="fs-3 fw-bolder">Request Application</h3>
<br>
<form action="" method="POST">
   
        <p>
           {{ form.name.label }} <br> 
           {{form.name()}}
        </p>


        <p>
           {{ form.reg_no.label }} <br>
           {{form.reg_no}}
        </p>

   
        <p>
           {{ form.email.label }} <br>
           {{form.email}}
        </p>


        <p>
           {{ form.blood_group.label }} <br>
           {{form.blood_group()}}
        </p>
    

   
        <p>
           {{ form.date_details.label }} <br> 
           {{ form.date_details() }}
        </p>
    

   
        <p>
           {{ form.address.label }} <br>
           {{ form.address() }}
        </p>    

   
        <p>
           {{ form.details.label }} <br>
           {{form.details()}}</p>
    

        <p>{{ form.submit() }}</p>

</form>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="/static/style.css">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="carousel.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    <title>{% block title %}Home{% endblock %}</title>      
  </head>

<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Carousel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>




<body>
<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-lg bg-light shadow-sm  p-3 mb-5 fixed-top bg-dark bg-body">
    <div class="container-fluid">
      <a class="navbar-brand text-danger" href="/">PlasmaPS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}                             
                <a class="nav-item nav-link text-info" id="request-board" href="/board">Request-Board</a>
                <a class="nav-item nav-link text-info" id="request" href="/request">Request</a>
                <a class="nav-item nav-link text-info" id="dashboard" href="/dashboard">Dashboard</a>
            {% else %}
                <a class="dropdown-item text-info" href="/donor-register">Sign up</a>
                <a class="dropdown-item text-info" href="/donor-login">Sign in</a>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

   
    {% with messages = get_flashed_messages(with_categories=true) %}
     <br/><br/>
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
      <div class="alert alert-danger ater-dismissable fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success ater-dismissable fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
    {% block content %}
    {% endblock %}

<div class="b-example-divider"></div>

<div class="container">
  <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-4">
      <h5 class="py-4 fs-4 fw-bolder text-info-emphasis">About</h5>
      <p class="pass fs-6 fw-light text-dark"> This is a project site created by me for my final year project. Don't take this site as something functioning as of yet. </p>
    </div>
    <div class="col mb-4"></div>
    <div class="col mb-4">
        <br><br><br><br><br>
        <ul class="nav justify-content-center border-bottom">
          <li class="nav-item"><a href="/terms" class="nav-link px-2 text-primary-emphasis">Terms and Conditions</a></li>
          <li class="nav-item"><a href="/faq" class="nav-link px-2 text-primary-emphasis">FAQs</a></li>
          <li class="nav-item"><a href="/privacy" class="nav-link px-2 text-primary-emphasis">Privacy</a></li>
        </ul>
    </div>
    <div class="col mb-4"></div>
    <div class="col mb-4 card-body">
      <p class="card-text text-info">
         <strong class="text-info-emphasis">Address : </strong>Anna University Regional Campus, Tirunelveli - 627007<br>
         <strong class="text-info-emphasis">Mail At : </strong>suswin@gmail.com<br>
         <strong class="text-info-emphasis">Contact Us : </strong>+91 8667414191<br>
      </p>
    </div>
 
  </footer>
</div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
   <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>-->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}">
    
    </script>

  </body>
</html>

website/templates/board.html
{% extends "base.html" %} {% block title %}Request Plasma{% endblock %}
{% block content %}
<br><br>
{% if current_user.id == 1 %}
    <h5 class="card-title">Welcome to The Request Board, Administrator. </h5>
{% else %}
    <h5 class="card-title">Welcome to The Request Board, {{current_user.name}}</h5>
{% endif %}

{% for entry in plasma %}
<div class="container">
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-header">Request Number : {{entry.id}}</div>
    <div class="card-body text-info" >
      <p class="card-text">
        <strong>Name :</strong>{{entry.name}}<br/>
        <strong>Email :</strong>{{entry.email}}<br/>
        <strong>Blood Group :</strong>{{entry.blood_group}}<br/>
        <strong>Date :</strong>{{entry.date_details}}<br/>
        <strong>Details :</strong>{{entry.details}}<br/>
        <strong>Address :</strong>{{entry.address}}<br/>
        {% if current_user.email == entry.email %}
           <a href="{{url_for('views.request_update', id = entry.id)}}" class="btn btn-primary btn-small">Update</a>
           <a href="{{url_for('views.delete', id = entry.id)}}" class="btn btn-danger btn-small">Delete</a>
        {% endif %}
        {% if current_user.id == 1 %}
           <a href="{{url_for('views.delete', id = entry.id)}}" class="btn btn-danger btn-small">Delete</a>
        {% endif %}
         
      </p>
    </div>
  </div>
</div>
{% endfor %}
       



{% endblock %}

website/templates/faq.html
{% extends "base.html" %} {% block title  %}FAQ's{% endblock  %}
{% block content  %}

<h2 class="text-center text-info-emphasis"> Frequently Asked Questions </h2>
<div class="container">

  <ul class="list-group">
    <li class="btn btn-info" data-bs-toggle="collapse" role="button" href="#gq"><strong>General</strong></li>
    
    <div class="collapse" id="gq">
      <div class="card card-body">
        <ul class="list-group">
          <li class="btn" data-bs-toggle="collapse" role="button" href="#gq1"><strong>1. How is plasma different from blood? </strong></li>
          <div class="collapse" id="gq1">
            <div class="card card-body">
              Plasma is a component of blood. Blood is made up of red blood cells, white blood cells, and platelets, all of which are suspended in plasma. Plasma is the liquid portion of blood and makes up about 55% of it. Plasma is typically a clear, yellowish color, though the color may vary between samples. For instance, blood plasma may appear more red, orange, or green depending on the donor. Reddish-orange plasma is often seen in smokers and greenish plasma may be more apparent for those who are pregnant, on certain birth-control medication, have rheumatoid arthritis, or are on other medications.
            </div>
          </div>
          
          <li class="btn" data-bs-toggle="collapse" role="button" href="#gq2"><strong>2. What is the differece between donating blood and donating plasma</strong></li>
          <div class="collapse" id="gq2">
            <div class="card card-body">
              The most common type of blood donation is called a whole blood donation. When you make a whole blood donation, you typically donate roughly one pint of blood. It can then be transfused in its original form or separated into its components, including plasma and red blood cells. Eligible donors age 19 and older can donate whole blood every 56 days. <br><br> When you donate plasma, blood is drawn from the arm and sent through a machine that automatically separates the plasma from the other blood components through a process called plasmapheresis. Then, the rest of your blood is returned back to you.
            </div>
          </div>

          <li class="btn" data-bs-toggle="collapse" role="button" href="#gq3"><strong>3. How does the body use blood plasma? </strong></li>
          <div class="collapse" id="gq3">
            <div class="card card-body">
              Plasma serves several important functions:
              <ul>
                <li>Maintains blood pressure and volume<li>
                <li> Supplies proteins for blood clotting </li>
                <li> Carries electrolytes throughout the body to muscles</li>
                <li>Supports cell function by maintaining proper pH balance</li>
              </ul>
              <br>
              When you donate plasma, it is a valuable resource to treat a variety of health problems. It is often used in treatments to save those suffering from medical emergencies including burns, shock, and trauma. Because plasma can increase blood volume and helps aid clotting, it is also provided to those with severe liver disease or clotting deficiencies. Plasma is also used by pharmaceutical companies as a component in certain medications.
            </div>
          </div>

          <li class="btn" data-bs-toggle="collapse" role="button" href="#gq4"><strong>4. Does plasma regenerate? </strong></li>
          <div class="collapse" id="gq4">
            <div class="card card-body">
              Yes, plasma will regenerate in about 48 hours after donation. This is much faster than it takes for whole blood to fully replenish, which takes about one to two months. The plasma in your blood is formed from water and salts absorbed through the digestive track. Remember to stay hydrated and avoid strenuous physical activity after donating plasma while it continues to replenish.
            </div>
          </div>

          <li class="btn" data-bs-toggle="collapse" role="button" href="#gq5"><strong>5. How often can i donate plasma? </strong></li>
          <div class="collapse" id="gq5">
            <div class="card card-body">
              Every 56 days, up to 6 times a year.
            </div>
          </div>
      </div>
    </div>
 
    <li class="btn btn-danger" data-bs-toggle="collapse" role="button" href="#rq"><strong>Risks</strong></li>
    
    <div class="collapse" id="rq">
      <div class="card card-body">
        <ul class="list-group">

          <li class="btn" data-bs-toggle="collapse" role="button" href="#rq1"><strong>1. Does donating plasma hurt? </strong></li>
          <div class="collapse" id="rq1">
            <div class="card card-body">
              You may experience mild discomfort when donating plasma, similarly to when donating blood or having blood drawn. Donors often compare the feeling of the needle to a slight pinch or bee sting.
            </div>
          </div>

          <li class="btn" data-bs-toggle="collapse" role="button" href="#rq2"><strong>2. What are the short-term side effects of donating plasma?  </strong></li>
          <div class="collapse" id="rq2">
            <div class="card card-body">
              For healthy adults who meet the donation eligibility requirements, donating plasma is generally a safe medical procedure, however you may face mild immediate side effects. Short-term plasma donation side effects include:
              <ul>
                <li><strong>Dehydration: </strong> Because plasma contains water, removing it may cause donors to experience mild dehydration after donation.</li>
                <li><strong>Dizziness or lightheadedness: </strong> Donating plasma may cause mild electrolyte imbalances because plasma contains a lot of salts, vitamins, and minerals (electrolytes) that help your body’s functions. </li>
                <li><strong>Fatigue: </strong>If you experience dehydration or electrolyte imbalances, you may also experience tiredness after donating plasma. </li>
                <li><strong>Bruising or discomfort: </strong> Bruising may occur at the site of the needle insertion, and you could experience some discomfort during the donation process. If you’re uncomfortable, you can speak with a clinician. </li>
                <li><strong>Infection or inflammation: </strong>Donating plasma comes with a slight risk of infection. Signs of infection include pain, swelling, or feeling of warmth at the site of the needle insertion.</li>
              </ul> 
            </div>
          </div>
        </ul>
      </div>    
    </div>  

    <li  class="btn btn-warning" data-bs-toggle="collapse" role="button" href="#dq"><strong>Donor related Queries</strong></li>
    
    <div class="collapse" id="dq">
      <div class="card card-body">
        <ul class="list-group">
    
          <li class="btn" data-bs-toggle="collapse" role="button" href="#dq1"><strong>1. What are the requirements to be a plasma donor? </strong></li>
          <div class="collapse" id="dq1">
            <div class="card card-body">
               Anyone in good health, between the ages of 18-74, who weighs at least 110 pounds, has no tattoos or piercings within the last 4 months, meets medical screening requirements, and has valid identification and a permanent address. Test negative for viruses that can be passed through blood, like HIV and hepatitis.
            </div>
          </div>

          <li class="btn" data-bs-toggle="collapse" role="button" href="#dq2"><strong>2. Who can donate plasma?  </strong></li>
          <div class="collapse" id="dq2">
            <div class="card card-body">
               Generally, anyone in good health, between the ages of 18-74, who weighs at least 110 pounds, has no tattoos or piercings within the last 4 months, meets eligibility and screening requirements, and has valid identification and a permanent address can donate plasma. <br/> If you have AIDS, have tested positive for HIV, or have done something in the past four months that puts you at risk of contracting HIV, you should not donate plasma. That includes:
               <ul>
                 <li>Anyone who has injected drugs, steroids, or other substances not prescribed by a doctor in the last four months.</li>
                 <li>Anyone who has engaged in sex for money or drugs in the last four months. </li>
                 <li>Men who have had sexual contact with other men in the last four months. </li>
               </ul>
               Similarly, if you have viral hepatitis or have had close contact with someone who does in the last 12 months, you should not donate plasma.
            </div>
          </div>

          <li class="btn" data-bs-toggle="collapse" role="button" href="#dq3"><strong>3. What happens during the plasam donation process? </strong></li>
          <div class="collapse" id="dq3">
            <div class="card card-body">
               Plasma donation usually takes about 90 minutes to two hours. If you have a preference for which arm is used, you can share it. You will have a cuff or tourniquet placed around your upper arm to increase the blood in your veins and the skin on the inside of your elbow will be cleaned. A sterile needle will be inserted into your vein. Whole blood will be collected and then run through a machine to separate the plasma from the other components. Once the plasma has been collected, a final return of white and red blood cells will be completed followed by an infusion of a saline solution.
            </div>
          </div>
        </ul>  
      </div>  
    </div>  
  </ul>
  
</div>

{% endblock  %}

website/templates/login.html
{% extends "base.html" %} {% block title %}login{% endblock %}
{% block content %}
<br>
<br>
<br>
<form action="" method="POST">
    <h3 align="centre">{{title}}</h3>
        <p>{{ form.email.label }} <br>
           {{ form.email }} </p>

        <p>{{ form.password.label }} <br>
           {{ form.password }} </p>

        <br><p>{{ form.submit() }} </p>
</form>

{% endblock %}

website/templates/recipient.html
{% extends "base.html" %} {% block title %}Plasma Drive Host Requirements{% endblock %}
{% block content %}

<br>
<h2 class="text-center fw-bolder fs-3">Am I eligible to host a drive?</h2> 
<p class="text-center fw-light fs-5">There are some requirements to be able to host a plasma drive. This is so that nobody does this to make money illegally or coerces others to give their plasma or other such things.</p>

<h3 class="py-4 fw-bolder fs-4"> Who all can host a plasma drive?</h3>
<ul class="list-group list-group-flush">
    <li class="list-group-item fs-6 ">1. <span class="text-seconadry">A liscensed Doctor</span>
    <li class="list-group-item fs-6 ">2. <span class="text-seconadry">An approved oraganisation</span>
</ul>

<h3 class="py-4 fw-bolder fs-4"> If you a liscensed doctor:</h3>
<p class="lead fs-6 text-danger">1. <span class="text-body-secondary">You need to have your doctor's liscense ready at hand.</span>
<p class="lead fs-6 text-danger">2. <span class="text-body-secondary">You need to have selected a venue that is reachable. If there are difficulties, then you must clearly give alternative ways to reach there.</span>
<p class="lead fs-6 text-danger">3. <span class="text-body-secondary">Must not force anyone to donate plasma.</span>
<p class="lead fs-6 text-danger">4. <span class="text-body-secondary">Volunteers must be there voluntarily.</span>

<h3 class="py-4 fw-bolder fs-4"> If you are an approves organisation:</h3>
<p class="lead fs-6 text-danger">1. <span class="text-body-secondary">You need to keep your healthcare liscense ready.</span>
<p class="lead fs-6 text-danger">2. <span class="text-body-secondary">Must provide detailed instructions to reach your venue</span>
<p class="lead fs-6 text-danger">3. <span class="text-body-secondary">The doctors your organisation employs for plasma collection must be a liscensed doctor and they are to have their liscense ready at all times.</span>


{% endblock %}